name: Documentation Checks
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .ci/.markdownlinkcheck.json
      - .markdownlint.yml
      - .github/workflows/documentation.yml
      - docs/**
      - go.mod

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    env:
      UV_THREADPOOL_SIZE: 128
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: YakDriver/md-check-links@a7b69aec87bb65faa4b35e41e51b1acedb5129c0 # v2.1.0
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.ci/.markdownlinkcheck.json'
          folder-path: 'docs'
          file-extension: '.md'
          base-branch: "main"
          check-modified-files-only: "yes"
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          args: 'docs'
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: cd .ci/tools && go install github.com/client9/misspell/cmd/misspell
      - run: misspell -error -source text docs/
